server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: stats_server_route
          uri: lb://stats-server
          predicates:
            - Path=/hit,/stats

        - id: user_admin_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_private_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        - id: comment_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**,/comments/**,/users/*/events/*/comments/**

        - id: event_route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**,/admin/events/**,/events/**,/users/*/events/**